# Generated by Django 4.2.4 on 2023-08-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_modes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemode',
            old_name='name',
            new_name='code',
        ),
    ]
