# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models

from speed_typing_backend.game_modes.models import GameMode


def create_fast_game_mode(apps, schema_editor):
    GameMode.objects.get_or_create(code='fast-game')


class Migration(migrations.Migration):
    dependencies = [
        ('game_modes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_fast_game_mode)
    ]
