# Generated by Django 4.2.4 on 2023-08-23 11:38
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_modes', '0003_gamemode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='multilanguage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='text_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GameModeExpectedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expected_texts.expectedtext')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_modes.gamemode')),
            ],
            options={
                'unique_together': {('game_mode', 'expected_text')},
            },
        ),
        migrations.CreateModel(
            name='GameModeDefaultTimeLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.IntegerField()),
                ('max_chars', models.IntegerField()),
            ],
            options={
                'unique_together': {('time_limit_seconds', 'max_chars')},
            },
        ),
        migrations.CreateModel(
            name='GameModeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='GameModeGameModeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_modes.gamemode')),
                ('game_mode_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_modes.gamemodetype')),
            ],
            options={
                'unique_together': {('game_mode', 'game_mode_type')},
            },
        ),
    ]
