# Generated by Django 4.2.4 on 2023-08-23 14:22

from django.db import migrations

from speed_typing_backend.game_modes.models import GameModeType, GameMode, GameModeGameModeType


def fix_game_mode_type_time(apps, schema_editor):
    game_mode_type, _ = GameModeType.objects.get_or_create(code=GameModeType.GAME_MODE_TYPE_TIME)
    game_mode = GameMode.objects.filter(code=GameMode.GAME_MODE_TIME_LIMIT_CODE)

    if game_mode.exists():
        game_mode = game_mode.first()
        GameModeGameModeType.objects.get_or_create(
            game_mode_type_id=game_mode_type.id,
            game_mode_id=game_mode.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('game_modes', '0006_gamemode_create_date'),
    ]

    operations = [
        migrations.RunPython(fix_game_mode_type_time)
    ]
