# Generated by Django 4.2.4 on 2023-08-21 11:48

from django.db import migrations


def add_fixture(apps, schema_editor):
    locale_model = apps.get_model('globals', 'Locale')

    locale_model.objects.get_or_create(
        id=1,
        iso='pl',
        defaults=dict(
            name='polski'
        )
    )

    locale_model.objects.get_or_create(
        id=2,
        iso='en',
        defaults=dict(
            name='english'
        )
    )

    locale_model.objects.get_or_create(
        id=3,
        iso='de',
        defaults=dict(
            name='german'
        )
    )


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('globals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_fixture)
    ]
