# Generated by Django 4.2.4 on 2023-08-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='locale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='globals.locale'),
        ),
    ]
