# Generated by Django 4.2.4 on 2023-08-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(max_length=8191),
        ),
    ]
