# Generated by Django 4.2.4 on 2023-08-21 11:48

from django.db import migrations


def add_fixture(apps, schema_editor):
    authors_model = apps.get_model('authors', 'Author')
    authors_model.objects.get_or_create(
        name='William Shakespeare'
    )


class Migration(migrations.Migration):
    initial = False

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_fixture)
    ]
