# Generated by Django 4.2.4 on 2023-08-21 13:03

from django.db import migrations

from speed_typing_backend.authors.models import Author


def add_fixture(apps, schema_editor):
    Author.objects.get_or_create(name='Creative Commons', url='https://creativecommons.org/')


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_url'),
    ]

    operations = [
        migrations.RunPython(add_fixture)
    ]
