# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0001_initial'),
        ('authors', '0003_author_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=16182)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
                ('locale', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='globals.locale')),
            ],
        ),
    ]
