# Generated by Django 4.2.4 on 2023-08-22 18:44

from django.db import migrations, models
import django.db.models.deletion

from speed_typing_backend.openai_integration.integration import OpenAI


def generate_texts(apps, schema_editor):
    OpenAI().create_expected_texts()


class Migration(migrations.Migration):

    dependencies = [
        ('expected_texts', '0002_expectedtext_original_text'),
    ]

    operations = [
        migrations.RunPython(generate_texts)
    ]
