# Generated by Django 4.2.4 on 2023-08-22 18:44

from django.db import migrations, models
import django.db.models.deletion

from speed_typing_backend.expected_texts.functions import create_texts_from_generator


def generate_texts(apps, schema_editor):
    create_texts_from_generator()


class Migration(migrations.Migration):

    dependencies = [
        ('expected_texts', '0002_expectedtext_original_text'),
    ]

    operations = [
        migrations.RunPython(generate_texts)
    ]
