# Generated by Django 4.2.4 on 2023-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expected_texts', '0002_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedtext',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
