# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_modes', '0001_initial'),
        ('expected_texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpm', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('time_ms', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('mistakes_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expected_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expected_texts.expectedtext')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_modes.gamemode')),
            ],
        ),
    ]
