# Generated by Django 4.2.4 on 2023-08-21 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expected_texts', '0003_expectedtext_active'),
        ('game_modes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cpm', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('average_cpm', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('best_cpm', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('games_played_count', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpm', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('time_ms', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('expected_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expected_texts.expectedtext')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_modes.gamemode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
