# Generated by Django 4.2.4 on 2023-08-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergame_create_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatistics',
        ),
    ]
