# Generated by Django 4.2.4 on 2023-08-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0002_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=127)),
                ('translation', models.CharField(max_length=254, null=True)),
                ('locale', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='globals.locale')),
            ],
        ),
    ]
